### ISSUE TITLE
Ascon80pq is still missing...

### ISSUE THREAD

**Issue by BigPanda97** [ascon/javaascon#1]
Will a Java version of Ascon80pq be added here too? I guess it shouldn't be too much work to modify Ascon128 to Ascon80pq. 😅

**Comment by meichlseder** [comment]
Hi, I added an implementation of Ascon-80pq.
(I didn't have time to run in-depth tests, so if you notice any inconsistencies, let me know.)

**Comment by BigPanda97** [comment]
@meichlseder Thanks, that's very nice of you. 😊
